name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-versions: ['8.3', '8.2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, libxml, mbstring, intl, xml, fileinfo, zip
          coverage: xdebug
          tools: composer, phpunit
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader
      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
      - name: Check for vulnerabilities
        run: composer security-checker
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer normalize
        uses: localheinz/composer-normalize-action@0.5.2
